### PR TITLE
Fix linked packages in workspaces with v3 lockfile

### PR DESCRIPTION
**Pull request by jtojnar**

### CODE REVIEW

**Review by WilliButz — APPROVED** [review]
Looks good, should the test also be added to the flake outputs?

**Comment by jtojnar** [comment]
Good catch.

**Comment by WilliButz** [comment]
I just ran a quick bisect to check why bitwarden-cli doesn't build anymore, seems to be caused by 5a135e387b938048aa5d447c206a8e4dcea0c6ed

**Comment by jtojnar** [comment]
Yeah, it does not like current versions of Node (20).  And bumping does not help, the repo was archived at Node 16.

**Comment by WilliButz** [comment]
Same issue with deckdeckgo, which didn't receive any updates since 2021. Found this post while looking for the cause: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported/73027407#73027407

**Comment by jtojnar** [comment]
I guess we could just remove the broken projects. Ideally we would find some up to date replacements but I could not be bothered :woman_shrugging:

**Pull request merged**
